//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("NoteModel", "FK_remindme_mydocs", "mydocs", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MyNoteBook_v1._0.mydoc), "remindme", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MyNoteBook_v1._0.remindme), true)]

#endregion

namespace MyNoteBook_v1._0
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class largedbEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new largedbEntities object using the connection string found in the 'largedbEntities' section of the application configuration file.
        /// </summary>
        public largedbEntities() : base("name=largedbEntities", "largedbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new largedbEntities object.
        /// </summary>
        public largedbEntities(string connectionString) : base(connectionString, "largedbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new largedbEntities object.
        /// </summary>
        public largedbEntities(EntityConnection connection) : base(connection, "largedbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<mydoc> mydocs
        {
            get
            {
                if ((_mydocs == null))
                {
                    _mydocs = base.CreateObjectSet<mydoc>("mydocs");
                }
                return _mydocs;
            }
        }
        private ObjectSet<mydoc> _mydocs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<remindme> remindmes
        {
            get
            {
                if ((_remindmes == null))
                {
                    _remindmes = base.CreateObjectSet<remindme>("remindmes");
                }
                return _remindmes;
            }
        }
        private ObjectSet<remindme> _remindmes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_ActivityLog> tbl_ActivityLog
        {
            get
            {
                if ((_tbl_ActivityLog == null))
                {
                    _tbl_ActivityLog = base.CreateObjectSet<tbl_ActivityLog>("tbl_ActivityLog");
                }
                return _tbl_ActivityLog;
            }
        }
        private ObjectSet<tbl_ActivityLog> _tbl_ActivityLog;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the mydocs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomydocs(mydoc mydoc)
        {
            base.AddObject("mydocs", mydoc);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the remindmes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToremindmes(remindme remindme)
        {
            base.AddObject("remindmes", remindme);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_ActivityLog EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_ActivityLog(tbl_ActivityLog tbl_ActivityLog)
        {
            base.AddObject("tbl_ActivityLog", tbl_ActivityLog);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NoteModel", Name="mydoc")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class mydoc : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new mydoc object.
        /// </summary>
        /// <param name="tid">Initial value of the tid property.</param>
        /// <param name="title">Initial value of the title property.</param>
        /// <param name="mydate">Initial value of the mydate property.</param>
        public static mydoc Createmydoc(global::System.Int32 tid, global::System.String title, global::System.DateTime mydate)
        {
            mydoc mydoc = new mydoc();
            mydoc.tid = tid;
            mydoc.title = title;
            mydoc.mydate = mydate;
            return mydoc;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 tid
        {
            get
            {
                return _tid;
            }
            set
            {
                if (_tid != value)
                {
                    OntidChanging(value);
                    ReportPropertyChanging("tid");
                    _tid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("tid");
                    OntidChanged();
                }
            }
        }
        private global::System.Int32 _tid;
        partial void OntidChanging(global::System.Int32 value);
        partial void OntidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String stuff
        {
            get
            {
                return _stuff;
            }
            set
            {
                OnstuffChanging(value);
                ReportPropertyChanging("stuff");
                _stuff = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("stuff");
                OnstuffChanged();
            }
        }
        private global::System.String _stuff;
        partial void OnstuffChanging(global::System.String value);
        partial void OnstuffChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime mydate
        {
            get
            {
                return _mydate;
            }
            set
            {
                OnmydateChanging(value);
                ReportPropertyChanging("mydate");
                _mydate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mydate");
                OnmydateChanged();
            }
        }
        private global::System.DateTime _mydate;
        partial void OnmydateChanging(global::System.DateTime value);
        partial void OnmydateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NoteModel", "FK_remindme_mydocs", "remindme")]
        public EntityCollection<remindme> remindmes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<remindme>("NoteModel.FK_remindme_mydocs", "remindme");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<remindme>("NoteModel.FK_remindme_mydocs", "remindme", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NoteModel", Name="remindme")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class remindme : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new remindme object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="remindmeon">Initial value of the remindmeon property.</param>
        public static remindme Createremindme(global::System.Int32 id, global::System.DateTime remindmeon)
        {
            remindme remindme = new remindme();
            remindme.id = id;
            remindme.remindmeon = remindmeon;
            return remindme;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> docTitle
        {
            get
            {
                return _docTitle;
            }
            set
            {
                OndocTitleChanging(value);
                ReportPropertyChanging("docTitle");
                _docTitle = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("docTitle");
                OndocTitleChanged();
            }
        }
        private Nullable<global::System.Int32> _docTitle;
        partial void OndocTitleChanging(Nullable<global::System.Int32> value);
        partial void OndocTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime remindmeon
        {
            get
            {
                return _remindmeon;
            }
            set
            {
                OnremindmeonChanging(value);
                ReportPropertyChanging("remindmeon");
                _remindmeon = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("remindmeon");
                OnremindmeonChanged();
            }
        }
        private global::System.DateTime _remindmeon;
        partial void OnremindmeonChanging(global::System.DateTime value);
        partial void OnremindmeonChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NoteModel", "FK_remindme_mydocs", "mydocs")]
        public mydoc mydoc
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<mydoc>("NoteModel.FK_remindme_mydocs", "mydocs").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<mydoc>("NoteModel.FK_remindme_mydocs", "mydocs").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<mydoc> mydocReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<mydoc>("NoteModel.FK_remindme_mydocs", "mydocs");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<mydoc>("NoteModel.FK_remindme_mydocs", "mydocs", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NoteModel", Name="tbl_ActivityLog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_ActivityLog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_ActivityLog object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static tbl_ActivityLog Createtbl_ActivityLog(global::System.Int32 id)
        {
            tbl_ActivityLog tbl_ActivityLog = new tbl_ActivityLog();
            tbl_ActivityLog.id = id;
            return tbl_ActivityLog;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TaskDone
        {
            get
            {
                return _TaskDone;
            }
            set
            {
                OnTaskDoneChanging(value);
                ReportPropertyChanging("TaskDone");
                _TaskDone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TaskDone");
                OnTaskDoneChanged();
            }
        }
        private global::System.String _TaskDone;
        partial void OnTaskDoneChanging(global::System.String value);
        partial void OnTaskDoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AtDate
        {
            get
            {
                return _AtDate;
            }
            set
            {
                OnAtDateChanging(value);
                ReportPropertyChanging("AtDate");
                _AtDate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AtDate");
                OnAtDateChanged();
            }
        }
        private global::System.String _AtDate;
        partial void OnAtDateChanging(global::System.String value);
        partial void OnAtDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AtTime
        {
            get
            {
                return _AtTime;
            }
            set
            {
                OnAtTimeChanging(value);
                ReportPropertyChanging("AtTime");
                _AtTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AtTime");
                OnAtTimeChanged();
            }
        }
        private global::System.String _AtTime;
        partial void OnAtTimeChanging(global::System.String value);
        partial void OnAtTimeChanged();

        #endregion

    
    }

    #endregion

    
}
